"use client";

import { motion } from "framer-motion";
import { Activity, Brain, Users, Dumbbell, Apple, Heart, Trophy, Zap } from "lucide-react";

export default function ServicesPage() {
  const services = [
    { icon: Users, title: "Personal Training", desc: "1-on-1 sessions with elite certified trainers tailored to your specific goals and body type." },
    { icon: Activity, title: "Group Classes", desc: "High-energy group workouts including HIIT, CrossFit, Yoga, and Pilates in premium studios." },
    { icon: Brain, title: "AI Nutrition", desc: "Hyper-personalized diet plans generated by our AI based on your genetics, preferences, and goals." },
    { icon: Dumbbell, title: "Strength Training", desc: "Comprehensive strength programs with form analysis and progressive overload tracking." },
    { icon: Zap, title: "Cardio Programs", desc: "Endurance building protocols utilizing state-of-the-art equipment and heart rate monitoring." },
    { icon: Heart, title: "Yoga & Flexibility", desc: "Mobility and flexibility routines to prevent injury, improve posture, and enhance recovery." },
    { icon: Trophy, title: "Body Transformation", desc: "Intensive 12-week complete overhaul programs combining fitness, nutrition, and mindset coaching." },
    { icon: Apple, title: "Sports Performance", desc: "Sport-specific conditioning for athletes looking to improve speed, agility, and power." }
  ];

  return (
    <div className="pt-32 pb-32 bg-black min-h-screen">
      <div className="container mx-auto px-4">
        <div className="text-center mb-20">
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-5xl md:text-6xl font-black mb-6"
          >
            OUR PREMIUM <span className="text-[#00D4FF]">SERVICES</span>
          </motion.h1>
          <p className="text-gray-400 max-w-2xl mx-auto text-lg">
            Discover a comprehensive suite of fitness solutions designed to elevate every aspect of your physical and mental well-being.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {services.map((service, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="bg-white/5 border border-white/10 rounded-3xl p-8 hover:bg-white/10 hover:border-[#00D4FF]/50 transition-all group"
            >
              <div className="w-14 h-14 bg-black/50 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <service.icon className="w-7 h-7 text-[#00D4FF]" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">{service.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed mb-6">{service.desc}</p>
              <button className="text-[#00D4FF] font-bold text-sm uppercase tracking-wider group-hover:text-white transition-colors">
                Learn More →
              </button>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
